### ISSUE TITLE
[question] 유비쿼터스 언어 설정에 소요되는 시간의 적정선

### ISSUE THREAD

**Issue by kth990303** [caffeine-library/Domain-Driven-Design#10]
## 질문
2장에서는 UBIQUITOUS LANGUAGE 설정 및 통일의 중요성을 강조하는 단원이라 생각합니다.
실제로 (기획, 개발 전체를 담당하는) 팀 내에서 용어가 통일된 때에 생산성이 증가하기 때문에 이는 중요하다고 생각됩니다.

다만, 유비쿼터스 언어를 통일하는 데에 드는 **시간이 굉장히 오래 걸리거나 의견차가 좁혀지지 않는 경우**가 존재할 수 있습니다.
제가 겪은 경험을 공유해보자면 아래와 같습니다.

### 지원자들의 과제를 자동 채점해주는 서비스
Q. `자동 채점 결과 수정 가능 여부`의 필드명(또는 도메인 용어)을 무엇으로 해야될까?
  - A: 결국 **수정 가능 여부**가 중심이다. `modifiable`이나 `isModifiable`로 하면 좋을 것 같다.
  - B: **자동 채점 결과**라는 의미가 누락되면 안된다. `recordModifiable`은 어떤가?
  - C: 자동 채점 결과를 우리가 직접 수정한다기보단, 채점이라는 시스템으로 인해 수정되는 것이다. `touchable`이나 `isTouchable`이 좋을 것 같다. (개발자 입장에서는) linux의 `touch` 명령어를 생각해봐도 이게 가장 의미가 적합하다.
  - A: `touch`는 리눅스 개발자가 보기에는 적합한 명령어지만, 그 외 개발자 또는 비전문가가 볼 때 전혀 알 수 없을 것 같다. **채점결과를 수정한다는 느낌보단 어루만진다는 느낌이 더 강하지 않는가?**
  - D: 그런데 잠깐. 다 떠나서 `~~able` 앞에 `is`를 붙이는 게 좋지 않을까?
  - E: 제발 밥 좀 먹고 하자. 시간이 오후 8시가 넘었다.
  - ... (얘기가 산으로 가기 시작)

아주 짧은 대화만을 적었는데 벌써 어지럽네요.
요약하자면 여러분들과 얘기를 나눠보고 싶은 주제는 아래와 같습니다.

1. 개발 용어를 정하는 데에 중요하게 여기는 점, 걸리는 시간을 여러분 팀 내에서 어느 정도로 잡고 진행하나요?
2. 만약 기획자와 개발자 사이에서 좋다고 생각되는 언어가 아예 다른 경우라고 합시다. 이 경우에도 언어를 하나로 통일하는 것이 좋을까요?

## 연관 챕터

#8

**Comment by leejaeseung** [comment]
1. 

새로운 용어를 정할 때 정말 애매하다 싶은 경우에만 슬랙에서 다같이 의견을 주고받고, 개발자들끼리의 용어 통일은 코드 리뷰 정도로만 하고 있습니다.
용어 통일을 위해 투자하는 시간도 리소스이다 보니 기획 단계에서 정의된 한글 용어를 영어로 바꿔 사용하는 정도인 것 같네요..
최근 개발간에 같은 대상에 대해 서로 다른 변수명으로 개발하고 있길래 용어 통일의 필요성을 느끼고 있습니다.
2.
네. 기획자-개발자 간의 용어 통일이 핵심이라고 생각합니다.
기획자-기획자 혹은 개발자-개발자 간의 용어 차이는 크게 문제가 되지 않을 수 있습니다. 서로 같은 지식을 공유하고, 바라보는 방향이 비슷할테니까요. (같은 직종이니)
하지만 기획자-개발자 의 경우는 모델을 바라보는 관점이 아예 달라집니다. 이는 설계나 추후의 프로젝트에도 영향을 줄 수 있다고 생각합니다.
DB 의 경우가 좋은 예시일 듯 한데, DB 의 테이블명이나 컬럼명은 기획의 의도를 잘 반영해야 추후의 추가적인 요구사항을 설계하기 수월합니다. 하지만 기획자의 의도가 충분히 반영되지 않는다면 애매하고 모호한, 삭제할 수도 없는 테이블/컬럼이 남게 되겠죠.

저희 팀에서도 항상 테이블명/컬럼명에 대한 고민과 후회를 가장 많이 하는 것 같네요.
실제로 제 첫 Task 에서 큰 고민없이 넣었던 컬럼이 사실은 기획과는 동떨어진 컬럼명이라 현재까지 프로젝트 전반적으로 애매해지기도 했습니다. 코드에선 DB 의 컬럼명을 써야하고, 기획에선 또 다른 용어를 써버리니..

**Comment by wooyounggggg** [comment]
Q) 책에서는 UL을 어떻게 활용해야 할 지 가이드를 제시하고 있어서 질문에 대한 답이 될 것 같은데,
실제 적용 사례에서는 어떻게 하고 있는지 궁금하신 걸까요?

**Comment by JasonYoo1995** [comment]
기본적으로 저희는 "기획자와 개발자 간에 용어를 통일하기 위한 시간"만을 위한 자리를 따로 잡진 않습니다.
그냥 자연스럽게 대화하다보면, 시간이 흐르면서 어느 순간부터 용어가 통일되기 시작하는데
그 용어가 결국 UL이 되고 있습니다.

(위에서 우영님께서 말씀하신 '책에서 말한 가이드'가
"구어로 말했을 때 자연스러운 용어를 UL로 채택하라"는 내용을 말씀하신 건지
아니면 다른 걸 말씀하신 건지 모르겠는데)

결국 저희도 "통일을 하자"라고 마련해놓은 자리에서 결정하는 게 아니라
일단 통일되지 않은 상태에서 계속 논의하는 과정 중 "어쩌다 보니 통일이 된" 용어가
'효율성'과 '자연스러움' 측면에서 가장 적절한 용어가 되었던 것 같습니다.

대부분은 기획에서 사용하는 단어가 자연스러운 단어가 많기 때문에, 기획의 용어를 따라가는 경우가 많지만
간혹 개발 쪽에서 사용하는 용어가 더 함축적이고 의사소통에서 효율적인 경우도 있기 때문에
개발 쪽 용어로 통일되는 경우도 있는 것 같습니다.

구현과 코드에서 사용하는 '변수명/컬럼명'까지 일일이 기획 쪽이 알 필요도 없고 알기 어렵기 때문에
그런 용어까지 꺼내와서 논의를 하진 않습니다.

물론, 이 책에서는 '기획 → 개발' 방향으로 '기획' 쪽의 성격을 반영하는 것 뿐만 아니라
'개발 → 기획' 방향으로도 '개발' 쪽의 성격도 반영하라고 하고 있지만
'개발'의 모든 것을 다 반영할 필요도 없고, 그럴 리소스도 없습니다.

우리에겐 시간과 에너지가 한정적이기 때문에
그 시간과 에너지가 허용하는 선 안에서 최대한 DDD 적인 철학을
실무에 실천하는 것이 최선이지 않을까 싶습니다.

**Comment by JasonYoo1995** [comment]
기본적으로 저희는 "기획자와 개발자 간에 용어를 통일하기 위한 시간"만을 위한 자리를 따로 잡진 않습니다.
그냥 자연스럽게 대화하다보면, 시간이 흐르면서 어느 순간부터 용어가 통일되기 시작하는데
그 용어가 결국 DDD에서 말하는 UL이 되고 있습니다.

(위에서 우영님께서 말씀하신 '책에서 제시한 가이드'가
31쪽의 '크게 소리내어 모델링하기' 파트에서 말한
"구어로 말했을 때 자연스러운 용어를 UL로 채택하라"는 내용을 말씀하신 건지
아니면 다른 걸 말씀하신 건지 모르겠는데)

저희는 계속 논의하는 과정 중 "어쩌다 보니 통일이 된" 용어가
'효율성'과 '자연스러움' 측면에서 가장 적절한 용어가 되었던 것 같습니다.

대부분은 기획에서 사용하는 단어가 자연스러운 단어가 많기 때문에, 기획의 용어를 따라가는 경우가 많지만
간혹 개발 쪽에서 사용하는 용어가 더 함축적이고 의사소통에서 효율적인 경우도 있기 때문에
개발 쪽 용어로 통일되는 경우도 있는 것 같습니다.

구현과 코드에서 사용하는 '변수명/컬럼명'까지 일일이 기획 쪽이 알 필요도 없고 알기 어렵기 때문에
그런 용어까지 꺼내와서 논의를 하진 않습니다.
(기획자들에겐 골격이 되는 설계만 공개하고, 세부 설계까지 공개하진 않습니다.)

물론, 이 책에서는 모델에 '기획' 쪽의 성격을 반영하는 것 뿐만 아니라
모델에 '개발' 쪽의 성격도 반영하라고 하고 있지만
현실적으로 UL에 '개발'의 모든 것을 다 반영할 리소스는 없습니다.

우리에겐 시간과 에너지가 한정적이기 때문에
그 시간과 에너지가 허용하는 선 안에서 최대한 DDD 적인 철학을
실무에 실천하는 것이 최선이지 않을까 싶습니다.

그래서 리소스가 부족해 통일하지 못한 부분은, 각자의 언어를 사용하면 된다고 생각합니다.

저희는 같이 일하는 사람들 중 DDD가 뭔지 모르는 사람들이 대다수인 상황이다 보니
개발자가 사용하는 모델과 기획자가 사용하는 모델을 통일하자고 설득하는 것은 쉽지 않네요.
(특히나, 신입 초짜가 시니어 분들을 설득하는 것은 더 어려운 일이죠)
다만, DDD를 모르는 사람들이 수긍할 수 있는 선에서는 최대한 DDD를 실천을 해보려고 합니다.

**Comment by wooyounggggg** [comment]
@JasonYoo1995 
경원님이 적어주신 것처럼, 처음에는 UL은 자연스러운 의사 소통 과정에서 발전하기 때문에 시간을 잡아놓고 진행할 문제가 아니라고 생각했습니다.

지금 다시 생각해보니, 아마 태현님이 궁금했던 부분은 `초기 UL 설정 시간`이 아닌가 싶어 저도 생각 남겨보겠습니다.

우선, 특정 영역의 전문가들만 사용하는 용어는 아래의 그림처럼 UL 바깥 영역에 두고 캡슐화하는 것이 좋은 것 같습니다.

<p align="center">
<img src="https://user-images.githubusercontent.com/19742896/212527323-22885e65-81fb-4d32-bb50-23ae00bf98ae.png" width=400>
</p>

그렇기에 UL은 통일하고, expert의 언어는 자유롭게 설정해도 되지 않을까 생각합니다.
