### ISSUE TITLE
[question] 문서는 이미 코드가 잘하고 있는 부분을 하려 해서는 안된다?

### ISSUE THREAD

**Issue by kth990303** [caffeine-library/Domain-Driven-Design#11]
## 질문

책에 글로 쓴 문서의 중요성을 언급하는 부분이 있습니다.
실제로 문서는 인수인계 시 개발자들이 작성한 코드에 대한 높은 이해 보장, 개발자 및 기획자들의 이해, 기획 방향에 대한 보존 등 매우 중요한 역할을 합니다.

다만 저는 책에서 말하고 있는 부분 중 `문서는 이미 코드가 잘하고 있는 부분을 하려 해서는 안된다`는 부분에 의문이 들었는데요.
왜 책에서 이렇게 말했을까 생각을 해보았습니다.

1. **코드만으로 충분히 이해가 가도록** 예쁜 설계와 가독성, 의미있는 변수 및 메서드명을 작성해야 한다.
2. 코드에서 설명하고 있는 부분을, 문서에서까지 설명하면 오히려 문서양이 많아지고 가독성이 떨어진다.

**1, 2번 모두 동의**합니다.
* * *
그럼에도 불구하고 **저는  `문서는 이미 코드가 잘하고 있는 부분을 하려 해서는 안된다`에 완전히 공감하진 못했습니다.**

### 우리나라 대부분의 사람들은 한국어에 익숙하다.
일단 우리나라는 **한국어를 사용**합니다. 그렇기 때문에 영어로 된 코드보다는 아무래도 한국어로 된 설명을 이해하기가 훨씬 편합니다. 예시로 실제로 코드에 주석을 다는 팀도 꽤 많이 있으며, 테스트 메서드명을 한글로 쓰거나 `@DisplayName`을 통해 한국어로 설명을 덧붙여주는 팀이 매우 많은 것으로 알고 있습니다. 변수 및 메서드명을 아무리 의미 있게 짓는다 하더라도, **한국어로 된 문서가 있다면 더더욱 이해하지 편리**하지 않을까요? 책의 저자인 에릭 에반스는 영어를 사용하고, 코드도 영어로 돼있기 때문에 이러한 말을 한 것은 아닐까요?

### 코드에 포함된 알고리즘 또는 로직이 꽤 어려운 경우라면?
또, 코드가 상당히 어려운 알고리즘을 포함하고 있다면? 아니면 코드만으로는 20줄이 되는데 한국어 문서로는 1~2줄로 충분히 설명할 수 있다면?
인간이 이해하기 편리하도록 만들어진 `객체지향`에서도 `캡슐화 및 추상화`를 강조하고 있습니다. 복잡하고 어려운 알고리즘이나 로직이 포함된 코드의 내용을 최대한 `캡슐화`하고, 해당 코드의 내용을 이해하기 쉽게 문서로 설명하여 `추상화`의 장점을 살린다면 오히려 더 좋지 않을까요?

* * *
위와 같은 장점들을 살릴 수 있다면 문서는 이미 코드가 잘하고 있는 부분을 더 쉽게 설명해줌으로써 모두가 쉽게 이해할 수 있는 더 좋은 역할을 해줄 수 있지 않을까 싶어 question을 남겨봅니다.

(추가로 든 생각인데, 위와 같이 문서로 더 쉽게 설명할 수 있다면... 코드가 잘하고 있는 부분에 속하지 않는 경우에 포함되는 것 같다는 생각도 드네요 😅 )

## 연관 챕터

#8

**Comment by wooyounggggg** [comment]
아직 책을 읽어보진 않아서, 정확히 작가가 어떤 뉘앙스로 얘기를 한 것인지는 모르겠지만 일반적인 내용일 것 같아서 의견을 남겨봅니다.

우선, 그 의미가 말씀해주신 아래의 내용
> 1. 코드만으로 충분히 이해가 가도록 예쁜 설계와 가독성, 의미있는 변수 및 메서드명을 작성해야 한다.
> 2. 코드에서 설명하고 있는 부분을, 문서에서까지 설명하면 오히려 문서양이 많아지고 가독성이 떨어진다.

이외에도 `단일 진실 공급원` 및 책의 서문에서 언급한 `애자일`의 관점에서 문서화가 갖는 단점을 생각한 것이 아닐까 생각됩니다.
- 참고: [단일 진실 공급원](https://ko.wikipedia.org/wiki/%EB%8B%A8%EC%9D%BC_%EC%A7%84%EC%8B%A4_%EA%B3%B5%EA%B8%89%EC%9B%90)

두 관점에서 저의 생각을 풀어보겠습니다.
### 단일 진실 공급원
DB 정규화, 코드 주석 및 documentation을 비롯하여 우리의 일상에서도 널리 쓰이는 개념이라고 생각합니다.
책 `클린 코드`에서는 주석을 정말 필요한 경우가 아니면 작성하지 말라고 하는데, 그 이유 중 하나로 시간이 지나면서 주석과 코드의 일관성이 틀어질 가능성이 있기 때문이라고 얘기합니다. 단일 진실 공급원의 원칙을 위배한다는 이야기죠.

이러한 양상은 프로젝트의 규모가 커질수록 더 잘 나타나는 것 같습니다. 구성원의 교체, 나태함, 시장의 변화, 리팩토링, 기술 발전, 개발 일정 등 다양한 이유로 코드는 계속해서 진화하기 때문에 문서로 지역적인 코드를 설명하는 것은 좋지 않다고 생각합니다.

물론 모든 경우에 그러하듯, 예외는 존재하기 때문에 프로젝트의 상황에 맞게 취사 선택할 필요는 있다고 생각합니다. 예를 들어 DB 반정규화를 하는 것은 단일 진실 공급원이 주는 이점보다 성능이 주는 이점이 더 크기 때문일 것입니다. 마찬가지로, 코드가 이미 잘 하고 있는 부분이지만 문서화 했을때 이점이 큰 경우도 분명 존재할 것이고, 이는 구성원의 합의와 명확한 근거가 필요한 부분이라 생각합니다. 이러한 경우가 어떤 경우가 있을지도 이어서 남기도록 하겠습니다.

### 애자일
애자일에서는 불필요한 문서화를 지양하고, 동작하는 코드를 만드는 것에 집중하자고 합니다. 애자일이 이러한 원칙을 내세우는 이유는, 아시다시피 폭포수 모델의 단점인 유연하지 못한 프로세스 때문일 것입니다.
불필요한 문서화는 프로젝트의 병목을 낳고, 변경을 꺼리게 하는 요인이 되기 때문에 이러한 관점에서 `불필요한 문서화를 하지 말자`의 논조로 받아들여집니다.

### 문서화의 이점이 큰 곳?
코드가 잘 하고 있는 일이라도, 문서화 했을 때의 이점이 크다고 생각하는 부분은 아래와 같은 것들입니다.
#### 변경이 잘 일어나지 않는 곳
- 프로젝트 아키텍처
- 시스템 아키텍처
- 프로젝트 전반에서 사용하는 패턴
- ...

#### 핵심 도메인 모델
도메인 모델은 변경되기 쉬울 수도 있지만, 팀에서 이를 공유하고 있다면 도메인 이해가 명확할 것이기 때문에
코드와의 sync가 어긋나지 않도록 유지보수 하면서 문서화 하는 것이 좋다고 생각합니다.

### 질문에 대한 생각
#### 우리나라 대부분의 사람들은 한국어에 익숙하다.
이 부분은 동감하지만, 영어로 된 코드를 한국어 문서로 쓰는 부분에서 일어나는 발번역(?) 때문에 오히려 코드를 있는 그대로 이해하기 어려운 경우도 생기는 것 같습니다. 아예 한국어 기반의 프로그래밍 언어를 만드는 것이 아니라면 어찌됐건 겪을 수 밖에 없는 리소스 낭비인 것 같네요. 미적분 배울때도 비슷한 생각을 했던 것 같네요 🥲 

#### 코드에 포함된 알고리즘 또는 로직이 꽤 어려운 경우라면?
알고리즘을 몇 가지 메서드로 나누고, descriptive한 변수를 만들고, 적절한 이름을 붙이는 등 가독성을 높이는 리팩토링 하는 편이 더 나은 솔루션일 것 같습니다. 이해하기 어려운 로직이라면 문서화 하더라도 어려운 것은 마찬가지 아닐까요?
저는 코드 그대로를 이해하는 것이 더 좋다는 생각입니다.

**Comment by kth990303** [comment]
@wooyounggggg 

좋은 의견 감사합니다.
질문에 대한 답변 부분을 읽고 추가로 드는 생각을 조금 더 적어보겠습니다.

### 1. 우리나라 대부분의 사람들은 한국어에 익숙하다.
> 이 부분은 동감하지만, 영어로 된 코드를 한국어 문서로 쓰는 부분에서 일어나는 발번역(?) 때문에 오히려 코드를 있는 그대로 이해하기 어려운 경우도 생기는 것 같습니다.

매우 동의합니다. 공감도 되는 부분입니다.

> 그리고 생각해보면 영어가 어려워서라기보단 프로그래밍 언어의 문법이 인간이 이해하기 쉬운 문장의 형태가 아니라서라는 생각도 들기는 하네요.
한글 프로그래밍 언어인 '씨앗'도 저에게는 여전히 이해하기 어려운 것 같습니다.

이 부분도 동의합니다.

위 두 부분 모두 동의가 되며 공감도 됩니다.
그렇지만 **이러한 이유가 오히려 저는 문서화가 더더욱 필요한 이유라 볼 수 있지 않을까 싶어서** 글을 남겨보게 됐습니다.
변수명 및 메서드명을 최대한 알아보기 쉽게 쓰거나, 한글명으로 된 프로그래밍 언어로 쓴다 해도 말씀해주신 부분들 때문에 이해하기가 충분히 어려울 수 있습니다. 그렇기 때문에 문서화로 다른 사람들이 알아보기 쉽게 요약하거나 정리해두면 인수인계 및 생산성 부분에서 이점을 가져올 수 있으리라 생각합니다.

### 2. 코드에 포함된 알고리즘 또는 로직이 꽤 어려운 경우라면?

> 알고리즘을 몇 가지 메서드로 나누고, descriptive한 변수를 만들고, 적절한 이름을 붙이는 등 가독성을 높이는 리팩토링 하는 편이 더 나은 솔루션일 것 같습니다. 이해하기 어려운 로직이라면 문서화 하더라도 어려운 것은 마찬가지 아닐까요?
저는 코드 그대로를 이해하는 것이 더 좋다는 생각입니다.

이 부분 역시 동의가 돼서 고민을 해보게 됐습니다.
코드 내의 알고리즘, 로직은 코드를 통해 이해해야 함에 동의합니다. 알고리즘을 전부 문서화하는 것은 너무 양이 방대해지고 오히려 어려울 수 있을 것 같아요.

그럼에도 불구하고 저는 코드 내에서의 로직이 조금 복잡하다면 문서화, 또는 약간의 주석은 필요하다고 보는 입장이기도 합니다.
메서드 분리 및 변수명과 메서드명을 descriptive하게 하더라도, 로직이 복잡한 경우는 이해하기 어려운 경우가 있을 수 있다고 생각하기 때문입니다. 
<img width="539" alt="image" src="https://user-images.githubusercontent.com/57135043/211751558-985c77b1-789e-41d5-a3d9-0ec4cefc6e41.png">

위와 같이 조금 복잡한 로직을 작성할 때, 로직이 꽤나 어려워서 결국 코드리뷰를 통해 로직을 이해시킨 경험이 있어서 이렇게 느낀 것일 수도 있겠네요..
다만 이 경우는 public method의 하위 메서드에 해당되는 private method인 만큼, 반드시 이해해야되는 로직은 아닌 부분은 아니어서 적절한 예시라 보긴 또 어렵네요.

정답이 없는 문제이다보니 참 어려운 것 같습니다.

**Comment by wooyounggggg** [comment]
이런 의사 결정에는 `문서화 시 얻는 이득 ÷ 문서화에 필요한 리소스`와 `팀의 가용 리소스`에 대한 정성적 평가가 중요한 것 같은데, 
그런 정보 없이 일반적으로 대화를 하다보니 답이 나오질 않는 것 같네요 ㅎㅎ 그래도 이런 고민을 해두면 나중에 컨텍스트가 확실해질 때 의사 결정에 도움이 되는 경우가 많은 것 같습니다.

제가 `문서화의 이점이 큰 곳?`이라고 쓴 부분도 문서화 했을 때 이득이 큰 정보들 위주로 서술한 것 같습니다.
팀의 리소스를 여기 분배하는 것이 올바른가? 에 대한 평가가 선행되어야 하고, 그 이후에 중요도를 내림차순 정렬해서 진행하는 것이 맞는 것 같네요.

다만 제가 속한 팀과 저의 경우에는 알고리즘이 복잡하게 짜여있어도, 디테일한 부분까지 문서화하지는 않는 것 같습니다.
리소스의 문제도 있지만, 팀 문화도 영향을 미치는 부분이 아닐까 생각합니다.

**Comment by leejaeseung** [comment]
정말 좋은 의견들 많이 남겨주셨네요 ㄷㄷ..
우영님 의견 중 `단일 진실 공급원` 이 제일 공감되는 부분이네요.
결국 실제로 의미가 있는 건 코드이고, 문서는 언젠가 코드와 불일치가 발생할 수 밖에 없겠죠..

저희 팀 같은 경우는 최근에 날을 잡고 문서 정리를 했었는데, 우영님의 글에서처럼 **변경이 되지 않는** 문서와 **수시로 변경되는 문서**를 나누는 작업을 했었습니다. (핵심 도메인에 대한 아키텍쳐 설계 등 과 프로젝트 히스토리 문서 등으로)
여기저기 퍼져있던 문서를 나눠놓으니, 문서의 변경성에 대한 경계가 확실해져서 코드에 주석을 짤 때 **변경되지 않는 문서**의 태그를 다는 등 문서에 대한 믿음(?)을 어느정도 얻을 수 있었네요.

**Comment by JasonYoo1995** [comment]
문서/코드/주석과 관련한 논의가 이루어지고 있는데요.
저도 이와 관련하여 저희 팀의 문화를 공유 드립니다.

## 주석
저희는 코드가 표현하지 못하는 내용은 코드 주변에 주석으로 남깁니다.
가끔 정말 어려운 알고리즘도 있어서, 이해를 돕기기 위해, 샘플 데이터와 함께 남기는 경우도 있고요.

만약 코드가 곧 바뀔 예정인 경우는 FIXME 주석이나 TODO 주석으로 어떻게 바뀌어야 하는지 남기고
언제 바뀔 예정인지 날짜를 함께 남기기도 합니다.

또한, 날짜/위치/국가/언어 등은 사용할 수 있는 라이브러리가 다양한데
해당 라이브러리에서 사용한 메서드는 어떤 표준에 기반하는지
해당 표준과 관련된 웹사이트 링크를 함께 주석으로 남깁니다.

알고리즘은 굉장히 단순한데, 코드만 보고는 도저히 이 코드가 왜 여기 있는지 이해할 수 없는 경우도 있습니다.
그럴 땐 그 코드가 들어간 이유가 담긴 confluence 문서의 링크를 주석으로 남기기도 합니다. 

저는 코드의 **유효기간** 혹은 문서의 **유효기간**이라는 단어를 쓰고 싶습니다.

코드의 유효기간이 짧으면, 오히려 주석으로 보충해줘야 할 필요가 커질 수도 있습니다.
일시적으로 생겼다가 사라질 부분이므로
코드를 작성한 사람이 아닌 다른 팀원들은 처음 알게되는 부분일 것이고
따라서 왜 생겼고 어떻게 바뀌어야 할지
코드와 가장 가까운 위치에서 직접적인 외칠 필요가 있습니다.

##문서

문서의 유효기간이 길면, 그 문서는 SSOT(Single Source Of Truth, 단일 진실 공급원)이 될 수 있습니다.
저희는 시퀀스 다이어그램이 몇 달 주기로 계속해서 바뀌고 있다 보니
시퀀스 다이어그램이 일관성이 없고, 최신화가 이루어지고 있지 않습니다.
그래서 SSOT 역할을 하는 시퀀스 다이어그램 페이지를 따로 만들기도 했습니다.

예전에 어떤 선임 분께서
`최신화 시키는 비용 < 시퀀스 다이어그램이 있어서 얻는 이득`일 때만
시퀀스 다이어그램을 그린다고 하셨던 것도 기억이 나네요.

도메인과 연관이 있는 **정책**적인 부분이나 **배경지식** 역시
코드가 표현할 수 없는 부분이므로 문서로 남기는 것이 중요할 것 같습니다.

## 요약
지금까지의 책 내용을 아래처럼 요약해보았습니다.
- 코드가 표현할 수 있는 부분을 최대화하라.
- 유효기간이 긴 문서는 작성하되, 유효기간이 짧은 문서는 코드가 표현하지 않는 부분일 경우에만 작성하라.
- 코드와 문서는 UL을 기반으로 작성해야 유효기간이 길어진다.
- 정제된 모델에서 추출된 UL을 사용할 수 있도록, 모델을 계속해서 정제해라.
이 가이드라인을 따르면, 리소스를 최대한 절약하는 방향으로 갈 것 같습니다.

**Comment by JasonYoo1995** [comment]
문서/코드/주석과 관련한 논의가 이루어지고 있는데요.
저도 이와 관련하여 저희 팀의 문화를 공유 드립니다.

## 주석
저희는 코드가 표현하지 못하는 내용은 코드 주변에 주석으로 남깁니다.
가끔 정말 어려운 알고리즘도 있어서, 이해를 돕기기 위해, 샘플 데이터와 함께 남기는 경우도 있고요.

만약 코드가 곧 바뀔 예정인 경우는 FIXME 주석이나 TODO 주석으로 어떻게 바뀌어야 하는지 남기고
언제 바뀔 예정인지 날짜를 함께 남기기도 합니다.

또한, 날짜/위치/국가/언어 등은 사용할 수 있는 라이브러리가 다양한데
해당 라이브러리에서 사용한 메서드는 어떤 표준에 기반하는지
해당 표준과 관련된 웹사이트 링크를 함께 주석으로 남깁니다.

알고리즘은 굉장히 단순한데, 코드만 보고는 도저히 이 코드가 왜 여기 있는지 이해할 수 없는 경우도 있습니다.
그럴 땐 그 코드가 들어간 이유가 담긴 confluence 문서의 링크를 주석으로 남기기도 합니다. 

저는 코드의 **유효기간** 혹은 문서의 **유효기간**이라는 단어를 쓰고 싶습니다.

코드의 유효기간이 짧으면, 오히려 주석으로 보충해줘야 할 필요가 커질 수도 있습니다.
일시적으로 생겼다가 사라질 부분이므로
코드를 작성한 사람이 아닌 다른 팀원들은 처음 알게되는 부분일 것이고
따라서 왜 생겼고 어떻게 바뀌어야 할지
코드와 가장 가까운 위치에서 직접적으로 외칠 필요가 있습니다.

## 문서

문서의 유효기간이 길면, 그 문서는 SSOT(Single Source Of Truth, 단일 진실 공급원)이 될 수 있습니다.
저희는 시퀀스 다이어그램(SD)이 몇 달 주기로 계속해서 바뀌고 있다 보니
SD이 일관성이 없고, 최신화가 이루어지고 있지 않습니다.
그래서 SSOT 역할을 하는 SD 페이지를 따로 만들기도 했습니다.

별개의 얘기지만
예전에 어떤 선임 분께서, 모든 시퀀스에 대하여 SD을 그리지 않고
`최신화 시키는 비용 < SD이 있어서 얻는 이득`일 때만
SD을 그린다고 하셨던 것도 기억이 나네요.

도메인과 연관이 있는 **정책**적인 부분이나 **배경지식** 역시
코드가 표현할 수 없는 부분이므로 문서로 남기는 것이 중요할 것 같습니다.

예전에 저희 팀에 합류하실 분을 뽑기 위해 면접관으로 참여한 적이 있는데
지원자께서 문서는 어차피 수정될 것이기 때문에 작성할 가치가 아예 없다는 식으로 말씀하셨습니다.
저희 팀은 문서를 굉장히 중요시 여기는 문화였기 때문에, 이 부분에서 상충되는 부분이 있었습니다.

저는 그 분의 대답이 단순히 쌩뚱 맞은 대답이라고만 생각했었는데
지금 생각해보니 XP(eXtreme Programming)의 맥락에서
문서는 최소화될 필요가 있다는 점을 이 책을 통해 처음 알게 되었습니다.

이제는 '문서는 리소스 절약 측면에서 최소화될 필요는 있지만
아예 없어서는 안 되고, 꼭 필요한 부분은 문서로 남겨야 한다'라는
균형 잡힌 시각을 가질 수 있게 된 것 같습니다

## 요약
지금까지의 책 내용을 아래처럼 요약해보았습니다.
- 코드가 표현할 수 있는 부분을 최대화하라.
- 유효기간이 긴 문서를 작성하되, 유효기간이 짧은 문서는 코드가 표현하지 않는 부분일 경우에만 작성하라.
- 코드와 문서는 UL을 기반으로 작성해야 유효기간이 길어진다.
- 정제된 모델에서 추출된 UL을 사용할 수 있도록, 모델을 계속해서 정제해라.

이러한 가이드라인을 따르면, 리소스를 최대한 절약하는 방향으로 갈 것 같습니다.

**Comment by emiling** [comment]
우영님께서 말씀주신 "단일 진실 공급원" 이라는 말이 많이 와닿았습니다 ㅎㅎ
사람이 직접 작성하게 되는 형식의 글은 결국 언젠가 변질되기 마련이고 이를 위해선 주기적인 개정이 필요하게 되죠.

> 제가 최근에  봤던 말중에 `문서와 같은 설명서를 왜 "메뉴얼(manual)"이라고 하는지 한 번 생각해봐야한다` 라는 말이 생각나네요. 

그래서 결국 동작하는 소프트웨어에서 가장 일관적인 것은 코드 그 자체이기 때문에 최대한 코드로 표현하려 하고 있지만
불가피하게 주석을 쓰는 경우도 발생합니다.

- 코드 리팩터링이 필요한 시점과 좀 더 고민해봐야 할 부분
- 왜 이러한 동작을 수행하는지에 대한 계약상의 문제
- 이러한 코드에 대한 비지니스적인 맥락 혹은 기술적인 한계로 인한 차선책 
- 등등...

이러한 부분에 대해선 PR 리뷰 코멘트로 남겨도 충분하다 혹은 주석으로는 불필요하다 등등의 의견도 있을 수 있겠지만
PR을 어떻게 관리하고 팀 내에서 이러한 히스토리를 어떻게 관리하는지에 따라 논의해볼 가치는 있을 것 같습니다.

반대로 문서로 관리해야하는 포인트들도 있는 것 같습니다.
저희가 현재 책으로 공부하고 있는 UL이나 핵심 모델에 대한 맥락과 용어 정리는 위키로 관리하고 있고
현제 시스템에서 의도하고 채택하고 있는 아키텍처나 비지니스 히스토리 등도 위키 관리 대상으로 생각하고 있습니다.
가볍게는 신규 입사자를 위한 장비 셋업과 같은 튜토리얼이나 서버 정보와 같은 것들도 있을 수 있겠습니다.

제가 생각한 결론은 상황에 따라 적절하게 채택하는 것이고 
팀원간의 합의를 도출해내는 과정에서 나오는 대화나 맥락들이 좀 더 중요하게 생각해볼 수 있는 요소일 것 같습니다.

**Comment by JasonYoo1995** [comment]
`이 코드는 이렇게 돌아갑니다`라는 주석 vs `이 로직이 들어간 "이유"`를 의미하는 주석

**Comment by JasonYoo1995** [comment]
- Git Blame 활용
  - 주석이 생긴 날짜
  - 누가 적은 주석인지

**Comment by leejaeseung** [comment]
## BDDMockito 사용 예시

토론 중에 나온 BDDMockito 의 저희 팀에서 사용 중인 예시 코드입니다.
```
feature("신규 그룹 디시를 생성한다.") {

    scenario("레시피 조회 실패") {
      Given("그룹 디시 생성 정보를 입력한다.")
      val groupDishCreator = createGroupDishCreator(
        recipeKey = recipe.key,
        name = dishEntity.name.get,
        description = dishEntity.description,
        applyAt = dishEntity.applyAt,
        dishTriggerFieldValueParams = Seq(dishTriggerFieldValueParam),
        dishActionFieldValueParams = Seq(dishActionFieldValueParam)
      )

      And("레시피 조회에 실패한다.")
      given(recipeRepository.findWithTriggerAndActionByKey(recipe.key)).willReturn(Future.successful(None))

      When("디시를 생성한다.")
      val result = sut.create(groupDishCreator).await

      Then("예외가 발생한다.")
      result.left.get mustBe a[InvalidRequest]
    }
}
```
다시 확인해 보니 scalatest 의 GivenWhenThen, feature/scenario 를 혼용해 사용하고 있었네요.. ㅎㅎ;;
Mockito 에서 when 메서드가 Given 로직에 사용되던 걸 BDDMockito 에선 given 으로 바꾸어 Given - When - Then 에 대한 가독성을 높이고 있습니다.

위처럼 각 테스트 시나리오를 주석처럼 일일이 달아주고 있어 테스트 코드를 짤 때 피로도가 조금 있지만, 테스트코드를 작성하면서 비즈니스 로직에 대한 파악을 먼저 할 수 있는 장점이 있던 것 같네요. 
또, 코드 리뷰를 할 때도 코드를 파악한다기보다 시나리오를 읽는 느낌이 들어 더 편했던 것 같습니다.
