### ISSUE TITLE
[question] 도메인 정책을 어떻게 구현하고 있나요?

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/Domain-Driven-Design#12]
## 질문
p.19 ~ p.20에서 `OverbookingPolicy`라는 정책으로 하여금, 일종의 validation을 수행하고 있습니다.
아마 도메인 레이어에서 이러한 역할을 하는 정책을 다들 사용하고 계실 것 같습니다.
저희 팀에서는 Specification이라는 개념이 이러한 정책의 역할을 하고 있는데, 여러분의 팀에서는 이러한 비즈니스 정책 요소들을 어떻게 정의하고 계신지 궁금합니다.

## 연관 챕터

#1

**Comment by JasonYoo1995** [comment]
- 구매 제한 조건 검증
  - 상품 판매 서버에서 검증하는 방법
  - 상품 정보 서버에서 검증하는 방법
  - 영수증 검증 서버에서 검증하는 방법
  - 게임 서버에서 검증하는 방법

- 검증 코드 위치
  - 모델 클래스 내부
  - 검증 관련 코드만 모여 있는 클래스 존재
  - 서비스 레이어에 검증

**Comment by leejaeseung** [comment]
핵심 정책은 도메인 모델 가까이, 변하기 쉬운 정책은 바깥 쪽에. 각 기능 별로 전문화
