### ISSUE TITLE
[keyword] 3장 - 모델과 구현의 연계

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/Domain-Driven-Design#16]
## 주제

`3장 - 모델과 구현의 연계`를 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터

#15

**Comment by kth990303** [comment]
## 한줄 요약
3장에서 말하고자 하는 점 역시, 기획자와 개발자가 함께 설계하는 것의 중요성이라 생각했습니다.

## 중요하다고 생각한 문장 및 키워드
### 1. 스쿼드 조직의 중요성
> 애플리케이션을 구현하기 시작했을 때 개발자는 얽혀 있는 연관관계(물론 분석가라면 알아볼 수 있었겠지만)를 트랜잭션 무결성을 준수하면서 조작할 수 있는, 저장 및 조회 가능한 단위로 해석할 수 없다는 사실을 금방 깨달았다. (중략) 그러나 기본적인 수준에서조차 모델은 구현에 대한 지침을 제공하지 못했다. (45p)

도메인 전문가가 생각하는 모델 설계, 개발자가 생각하는 모델 설계는 서로 다를 확률이 훨씬 높다고 생각합니다.
1장에서도 계속해서 언급돼서 나온 내용이지만, `특정 개념의 중요성과 그에 따른 추상화의 정도`, `예상한 구현 난이도 및 생산성`(이 부분은 심지어 개발팀에게 주어진 인력, 비용, 기한에 따라서도 굉장히 달라질 것 같아요)를 서로 다르게 생각할 확률이 높기 때문이죠. 

결국 모델 설계는 1장부터 강조했듯이 다같이 설계하면서 점점 이해도를 높여가며 설계를 리팩터링(?)해나가는 과정이 필수적이라 봅니다.

---

### 2. 모델과 구현의 연계
또, 기획자와 개발자가 함께 하지 않는다면 그에 따라 구현 난이도 역시 증가할 것이라고 말하고 있다 생각합니다.
> 설계 혹은 설계의 주된 부분이 도메인 모델과 대응하지 않는다면 그 모델은 그다지 가치가 없으며 소프트웨어의 정확함도 의심스러워진다. 동시에 모델과 설계 기능 사이의 복잡한 대응은 이해하기 힘들고, 실제로 설계가 변경되면 유지보수가 불가능해진다. (49p)

> 구현을 모델과 그대로 묶으려면 보통 객체지향 프로그래밍과 같은 모델링 패러다임을 지원하는 소프트웨어 개발 도구와 언어가 필요하다. (50p)

모델 중심적, 객체 중심적, DDD(도메인 중심적)으로 개발하여 객체에게 자율성과 적절한 책임을 부여한다면 훨씬 책임이 줄어들 수 있겠죠. 이는 52~58p에서 소개된 PCB 예제에서도 강조되어 안내되고 있다고 생각합니다. 객체의 일부 책임만 변경하면 되는 부분을, (만약 절차지향적으로 작성한다면) 수천개의 네트 각각의 규칙을 일일이 해당 코드를 찾아서 수정해야 하는 번거로움으로 다가올 수도 있는 것처럼요. 

모델 중심적으로 도메인 전문가와 개발자가 함께 적절한 추상화 및 응집성을 고려하여 설계한다면 구현도 쉽고 편리하게 작성할 수 있으며, 도메인 전문가가 코드를 보며 이해할 수 있을 확률도 높아진다고 말하고 있다고 생각합니다.

---

### 3. 모델의 중요성
즐겨찾기 예제 (58~59p)를 통해 모델의 중요성을 느낄 수 있었습니다. 
사실 UI/UX의 중요성을 더 크게 느끼긴 했지만요ㅋㅋ

## 추가로 든 생각
실제로 스쿼드 조직으로 개발하지 않는 팀과 스쿼드 조직으로 개발하고 있는 팀이 우리 스터디에 모두 존재하는 것으로 알고 있는데요. 한 번 스프린트 분기별로 회의 과정이 어떻게 진행되는지 얘기를 나눠보는 것도 좋을 듯하단 생각이 들었습니다.

**Comment by JasonYoo1995** [comment]
## 소제목 별 요약

- **좋은 모델**이란? (p.49)
  > 이 접근법에는 **분석과 설계 관점에서 모두 효과적인 모델**이 필요하다.
  모델이 구현에 대해 비현실적으로 보인다면 새로운 모델을 찾아내야만 한다.
  모델이 도메인의 핵심 개념을 충실하게 표현하지 않을 때도 새로운 모델을 찾아내야만 한다.
  그래야만 모델링과 설계 프로세스가 단 하나의 반복 고리를 형성할 수 있다.

- Model Driven Design에 효과적인 모델링 패러다임, **OOP** (p.51)
  > **객체지향 프로그래밍**은 모델링 패러다임에 근거하고 모델의 구성요소에 대한 구현을 제공하기 때문에 매우 효과적이다.

- 사용자에게 내부 모델을 드러내라 (p.58)
  > 즉, **사용자 모델**과 **설계/구현 모델**이 별도로 존재한다는 것이다.

  - 사용자 모델과 설계/구현 모델이 별도로 존재하지 않고, **하나의 모델**로 일치하는 것이 좋다는 내용.

- **실천적 모델러**(**Hands-on Modeler**)란? (p.60)
  > 누가 좋아하건 말건 **프로그래머**가 곧 **모델러**다.
  그러므로 프로그래머가 훌륭한 모델링 업무를 할 수 있게 프로젝트를 구성하는 것이 바람직하다.

  - 실천적 모델러란, **구현 쪽의 특성을 고려**하여 모델을 만드는 설계자이다.
  - **프로그래머**가 모델러 역할에 참여하는 것이 바람직하다.

## 전체 요약을 한 그림으로

- **모델 주도 설계**(**Model Driven Design**)란?

  ![image](https://user-images.githubusercontent.com/66045861/215303325-72c6c046-d7d5-4606-b7b5-7ccea33e7685.png)
  - 모델이 여러 단계에 걸쳐 있는 것은 비효율적
  - 하나의 모델만 사용하는 것이 효율적 (**단일 모델**)
  - 프로그래머는 **구현** 뿐만 아니라 **모델링**에도 참여하는 것이 바람직
