### ISSUE TITLE
[question] DDD와 MSA 간의 연관성

### ISSUE THREAD

**Issue by JasonYoo1995** [caffeine-library/Domain-Driven-Design#18]
## 질문

DDD와 MSA 간의 연관성에 대해 나눠보면 좋을 것 같습니다.

## 참고

에릭 에반스의 **도메인 주도 설계**를
[도메인 주도 설계로 시작하는 마이크로서비스 개발 : 핵심 개념과 패턴 설계 구현으로 배우는 DDD와 MSA](https://product.kyobobook.co.kr/detail/S000001766464) 라는 책과
연결지어 생각하면 좀 더 폭이 넓어지는 것 같습니다.

**Comment by JasonYoo1995** [comment]
- OOP / DDD / MSA 의 공통점 : 복잡한 비즈니스 로직에 대해 유지 보수하기 용이하도록 하는 패러다임이다.

**Comment by kth990303** [comment]
저는 DDD, MSA에 대한 생각이 계속해서 바뀌고 있는데요.
`예전의 저`는 사실상 MSA에 있어서 DDD는 필수적이고, 더 나아가서 DDD가 MSA의 일부라고 생각했던 적이 있었습니다.
`지금의 저`는, DDD는 도메인 주도 **설계**, MSA는 **아키텍처** 라는 점에 초점을 맞춰서 접근하는 편입니다.
`이후의 저`는 또 생각이 달라질 수도 있겠네요 ㅎㅎ

즉, MSA에 있어서 DDD가 필수적이지도 않고, 일부도 아니고 다른 것임이 분명하다고 생각합니다. 
**하지만 경원님이 남겨주신 코멘트처럼 저도 둘은 분명 상관관계가 있으며 같이 어우를 때 시너지를 낸다고 생각**합니다. (#17 헥사고날 아키텍처 - CQRS, CQRS - Event Sourcing 처럼 말이죠)

DDD는 도메인에 초점을 맞춰서 설계하는 것이며, 이는 마이크로서비스 아키텍처뿐만 아니라 모놀로식에서도 충분히 적용할 수 있는 설계라 생각합니다.
MSA는 각 기준에 따라 독립적인 생명주기를 가지는 서비스들의 집합체를 지니는 아키텍처이므로, 각 서비스들을 분류할 때 **DDD 관점으로 aggregate 또는 컨텍스트 별로 나누면 더 좋겠다**고 생각이 들었습니다. 이렇게 하면 도메인 전문가도 더더욱 자신의 전문 분야에 집중할 수 있게 될 것이며, 개발자도 타 서비스와의 의존성을 줄이고 독립적으로 개발하면서 고가용성을 지닐 수 있게 되겠죠.

---
 
> 제가 생각하는 OOP / DDD / MSA 의 공통점은
셋 다 복잡한 비즈니스 로직을 담은 서비스의 규모가 커져도 유지 보수하기 용이하도록 도와주는 패러다임이라는 것입니다. 

경원님의 말씀에 일부 동의합니다.
일부라고 생각한 이유는 MSA는 서비스의 규모가 작을 때는 오히려 불필요한 생산성을 유발한다고 생각하기 때문입니다. 
(`서비스의 규모가 커져도 `-> `서비스의 규모가 너무 커져 모놀로식으로 개발하기 힘들어졌을 때` 로 바뀌면 전적 동의할 것 같아요)
이에 대한 재밌는 글이 있어서 공유해봅니다.
[전 GitHub CTO, "지난 10년간 가장 큰 아키텍처 실수는 풀 마이크로서비스로 전환한 것"](https://twitter.com/jasoncwarner/status/1592227285024636928) 

DDD는 서비스의 규모와 상관없이 유지보수 및 팀 내 구성원(개발자, 기획자 등)들의 이해를 높이고 더 효율적인 개발을 하기 위해 생겨난 설계론적 방법이라 생각하기 때문에 이 부분도 전적이 아닌 일부 동의합니다.

---

근데 사실 소프트웨어에 은탄환은 없다고 생각해서 스터디원들 모두 생각이 다 다를 것이라 생각하는데요.
얘기 나눠보면 꽤 재밌을 것 같네요. (실제로 개발자들은 일상얘기할 땐 조용하다가, 술자리에서 갑자기 개발 주제(ex.`classicist vs mockist`, `dry vs damp`) 나오면 5시간동안 토론하기도 하는거처럼 말이죠 😅 저랑 제 지인들 얘기입니다 ㅋㅋ)

**Comment by JasonYoo1995** [comment]
제 의도는
"OOP, DDD, MSA는 도메인이 복잡할 때 유용하게 쓰일 수 있다" 였고
"도메인이 복잡할 때는 항상 OOP, DDD, MSA가 유용하다"는 아니었습니다

뭔가 그 정도 디테일까지 표현하진 않아서 오해를 살만 했네요

각각의 차이점에 대해 명확하게 생각해볼 수 있어서 좋았습니다
좋은 커멘트 감사합니다!

**Comment by JasonYoo1995** [comment]
MSA에서 한 서비스의 범위?
설계 단계에서
- 결합도나 의존성이 높아 보이면, 한 서비스로 묶고
- 결합도나 의존성이 거의 없는 경우에만, 다른 서비스로 분리하는 게 어떨지

**Comment by JasonYoo1995** [comment]
BFF : https://tech.kakaopay.com/post/bff_webflux_coroutine/

**Comment by JasonYoo1995** [comment]
<img width=700 src=https://user-images.githubusercontent.com/66045861/216800809-096c0986-61da-4c99-8760-220c52c1acba.png>

출처 : [도메인 주도 설계로 시작하는 마이크로서비스 개발 : 핵심 개념과 패턴 설계 구현으로 배우는 DDD와 MSA](https://product.kyobobook.co.kr/detail/S000001766464)
