### ISSUE TITLE
[keyword] 1장 - 지식 탐구

### ISSUE THREAD

**Issue by JasonYoo1995** [caffeine-library/Domain-Driven-Design#2]
## 주제

'1장 - 지식 탐구'을 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터

#1

**Comment by emiling** [comment]
### 서문 

- 이 책의 전제는 다음과 같다 (p. 33)
  - 대부분의 소프트웨어 프로젝트에서는 가장 먼저 **도메인**과 **도메인 로직**에 집중해야한다
  - 복잡한 도메인 설계는 **모델**을 기반으로 해야한다
- **나는 모든 독자가 1장 뿐만 아니라 1부를 소개하는 내용부터 읽기를 권한다**. 그 이후로는 핵심적인 내용은 아마도 **2,3,9,14장 일 것이다** (p.39)

### 제 1부. 동작하는 도메인 모델 만들기
#### 모델
- 대상을 **단순화** 한 것이다 
- 추상화, 그 밖의 중요하지 않은 세부사항에는 주의를 기울이지 않음
- 지식을 선택적으로 단순화하고 의식적으로 구조화한 형태
- 모델을 통해 정보를 이해하고 문제 자체에 집중할 수 있다

#### 도메인
- 사용자가 프로그램을 사용하는 대상 영역

#### 도메인 모델
- 어떤 특정한 다이어그램이 아닌 그 다이어그램이 전달하고자 하는 아이디어
- 도메인 전문가의 머리속에만 존재하는 지식이 아닌 해당 지식을 엄격하게 구성하고 선택적으로 추상화한 것

#### 소프트웨어의 본질
- 해당 소프트웨어의 사용자를 위해 도메인에 관련된 문제를 해결하는 능력
- 그러나 대부분 도메인 연구에 관심이 없음 (_기술자들은 자신의 기술력을 훈련할 수 있는 정량적인 문제를 좋아한다 ㅋㅋ_)
- 복잡성을 해쳐나가는 명쾌한 모델을 만들어나가자

**Comment by kth990303** [comment]
### 내가 생각하는 해당 챕터에서 강조하는 키워드
- 도메인에 대한 관심
- 모델에 대한 추상화

### 도메인에 대한 관심
- 프레임워크, DB, cache 여부 등과 같은 세부사항이 아닌 도메인 및 모델에 대한 유스케이스가 본질이다. (p.14 + 유스콘 2022 세미나 일부 발췌)
  - (주관적인 생각) 도메인은 위와 같은 세부사항에 의존해선 안된다. 외부 기술 및 라이브러리 의존성은 DIP 원칙을 이용하여 추상화 기법을 통해 분리해야 한다. 
  - 도메인에 대한 이해가 충분할수록 한층 더 높은 수준으로 정제된 모델로 이어진다. 
    - `설계를 이러한 수준까지 끌어올리려면 프로그래머와 그 밖의 관련된 모든 이가 초과예약의 특성을 단순히 불분명한 계산에 불과한 것이 아니라 별개의 중요한 업무 규칙임을 알아야만 할 것이다.` (p.20)  

### 모델에 대한 추상화
- 인간은 완벽하지 않은 동물이다. 따라서 도메인에 대한 모든 지식을 머릿속으로 정리하기란 불가능에 가까움. 개발에 중요한 규칙 및 모델을 추상화하고 이에 맞게 작업하는 것이 중요 (p.16 ~ 17)  

### 결론
- 1장 내용을 한 마디로 요약하자면, 주로 `도메인 및 모델에 대한 이해도가 중요하다!` 라고 어필하는 것 같다. 
- DDD(도메인 주도 설계)를 하기 위한 전제 조건으로 어떻게 보면 당연하지만, 어떻게 보면 가장 어려운 부분 중 하나라 생각된다.
  - 완벽하게 이해하고 설계한 후에 개발하는 것? 그것은 개인적으론 불가능이라 생각한다.
  - 그렇다고, 아무 회의도 없이 바로 개발에 도입하는 것 또한 잘못됐다고 생각한다.
  - 그렇기 때문에 최종적으로 초반에 도메인 전문가(또는 기획자)와 개발자와의 의사소통을 통해 명확하게 정한 후에, 개발하면서 더 잘 이해해나가는 것이 중요하다고 생각된다.

**Comment by leejaeseung** [comment]
도메인 주도 설계에 대한 개인적인 생각을 적어 봅니다.

## 도메인 주도 설계란?

도메인 주도 설계란 현실세계의 문제에 초점을 두고 여러 분야의 전문가가 같은 모델을 공유하며 해결해가는 거라고 생각된다.
여러 분야의 전문가가 같은 모델을 공유해야 하니, **유비쿼터스 언어**나 **도메인 모델**같은 현실세계와 밀접한 개념들을 사용한다.

왜 할까?
- 개발자가 아닌 기획자의 입장에서 생각하는 법을 배운다.
ex) 개발자는 보통 더 복잡한 설계, 추상화 등등을 좋아한다. 하지만 기획자에겐 불필요할 수 있다.(굳이?)
- 다양한 시각으로 문제를 바라보므로 생각지 못한 해결책이 나올 수 있다.
- 도메인 주도 설계의 반대대는 극단적인 예로 외주 개발을 들 수 있을 것 같다. 기획자와 개발자는 소통하지 않고 서로의 문제만 해결한다. 결국 서로가 바라보는 관점이 달라 끝없이 피드백을 주고받아야 될 것이다.
도메인 주도 설계는 서로 같은 모델의 관점에서 문제를 해결하니 불필요한 작업을 줄일 수 있다.

기획자와 개발자가 한 팀으로 일하면 최소한의 도메인 주도 개발을 하고 있는게 아닐까?

**Comment by wooyounggggg** [comment]
## 서문, p.7 ~ p.13
> 이 책은 특정 방법론에 매여 있지 않지만 “애자일 개발 프로세스’라는 새로운 진영을 지향한다.
> 특히，아래의 두 가지 실천법이 프로젝트 수행 중에 일어나야 한다고 가정한다.
> 1) 개발은 반복주기를 토대로 진행돼야 한다
> 2) 개발자와 도메인 전문가는 밀접한 관계에 있어야 한다  

이 내용과 관련하여, [객체지향 개발 방법론 강의](http://dslab.konkuk.ac.kr/Class/2022/22SMA/Lecture%20Note/OOAD(2022).pdf)에서 `고객이 요구사항 설정에 참여해야 한다`는 agile의 속성을 생각해볼 수 있었음.
<p align="center"><img src="https://user-images.githubusercontent.com/19742896/211073226-b7e67191-042d-4224-aa5d-1b2ec98e69b5.png" width=600></p>

**Q. 도메인 전문가 != 고객일 때는 어떻게 해야할까?**

---

## p.13 효과적인 모델링의 요소
1. 모델과 구현의 연계
    - 초기 프로토타입 개발
    - 피드백 -> 구현 -> 피드백 -> ... 의 과정이 반복되어야 함 
2. 모델을 기반으로 하는 언어 정제
    - 유비쿼터스 언어를 얘기하는듯 함
3. 풍부한 지식이 담긴 모델 개발
    - 단순한 데이터 스키마 이상의 역할을 하는 모델 
4. 모델의 정제
5. 브레인스토밍과 실험

**Comment by JasonYoo1995** [comment]
- 도메인 전문가의 후보
  - 특정 분야의 전문가
  - 기획팀
  - 사업팀
  - 사용자
  - ?
