### ISSUE TITLE
[question] 옵저버 패턴

### ISSUE THREAD

**Issue by emiling** [caffeine-library/Domain-Driven-Design#22]
## 질문

하위 계층의 객체가 상위 수준의 객체와 소통하기 위한 방법으로 옵저버 패턴을 얘기하고 있는데요, 
한 번 언급된 김에 정리하고 가면 좋을 것 같습니다.

#### 배경
- 각 계층은 의존성을 오직 한 방향으로만 둬서 느슨하게 결합된다.
    - 상위 계층은 하위 계층의 공개 인터페이스를 호출하고 하위 계층에 대한 참조를 가지며, 
       일반적으로 관례적인 상호작용 수단을 이용해 하위 계층의 구성요소를 직접적으로 사용하거나 조작할 수 있다
    - 하위 계층의 객체가 상위 수준의 객체와 소통하는 경우는 콜백이나 **OBSERVER 패턴** 처럼 
       계층 간에 관계를 맺어주는 아키텍처 패턴을 사용할 수 있다

## 연관 챕터

https://github.com/caffeine-library/Domain-Driven-Design/issues/19

**Comment by emiling** [comment]
## Observer Pattern

객체의 상태 변화를 관찰하여 변화가 발생하면 변화를 통지받고 자동으로 갱신될 수 있게 한다. 

![image](https://user-images.githubusercontent.com/30731518/216801052-cd3366ec-e243-4847-95ac-ed99a92d1411.png)

- **Subject**에 여러 **Observer**를 등록(attach)한 뒤 이벤트를 공지(notify)하게 되면 각 루프를 돌면서 Observer를 갱신(update)한다.
- Subject와 Observer가 인터페이스를 통해 느슨한 결합을 갖도록 하는 것이 포인트

### 구현

- Observer

```kotlin 
interface Observer {
    fun update(message: String)
}

class Insight: Observer {
    override fun update(message: String) {
        println(message)
    }
}

class NewYorkTimes: Observer {
    override fun update(message: String) {
        if(message.contains("money")) println("Breaking news from Insight! $message")
    }
}

class Guardian: Observer {
    override fun update(message: String) {
        if(message.contains("queen")) println("Yet more news in London... $message")
    }
}
```

- Subject

```kotlin
interface Subject {
    fun attach(o: Observer)
    fun detach(o: Observer)
    fun notify(message: String)
}

class TweetFeed: Subject {
    private val observers: MutableList<Observer> = mutableListOf()
    override fun attach(o: Observer) { observers.add(o) }
    override fun detach(o: Observer) { observers.removeIf { it == o } }
    override fun notify(message: String) { observers.forEach { it.update(message) } }
}
```
#### 실행

```kotlin
val musk = TweetFeed();

// register observers 
musk.register(Insight())
musk.register(NewYorkTimes())
musk.register(Guardian())

// notify event
musk.notify("Even though Startlink is still losing money & other companies are getting billlions of taxpayer $, we'll just keep funding Ukraine govt for free")
musk.notify("Doge")
```


### 예시 

https://docs.spring.io/spring-framework/docs/5.3.7/reference/html/core.html#context-functionality-events

Spring ApplicationContext 이벤트 핸들링 시에 ApplicationListener 인터페이스를 구현한 bean이 컨텍스트에 배포되면 ApplicationEvent가 ApplicationContext에 발행될 때마다 해당 bean으로 알람 전송

> Event handling in the ApplicationContext is provided through the ApplicationEvent class and the ApplicationListener interface. If a bean that implements the ApplicationListener interface is deployed into the context, every time an ApplicationEvent gets published to the ApplicationContext, that bean is notified. **Essentially, this is the standard Observer design pattern.**

**Comment by kth990303** [comment]
프록시 패턴 vs 옵저버 패턴

프록시 패턴: 대리자 역할, 부수 로직 첨가 및 묶어서 한번에 가능
옵저퍼 패턴: 하위 객체가 타 객체 또는 상위 객체한테 메서드 호출 및 전달
