### ISSUE TITLE
[additional] 분산 시스템을 위한 유일 ID 생성기 설계

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/Domain-Driven-Design#29]
## 연관 챕터
#24 

## 조사 내용
책에서 유일한 ID를 생성하는 기술에 대해서는 넘어갔는데, 가상 면접 사례로 배우는 대규모 시스템 설계 기초의 [이슈](https://github.com/caffeine-library/system-design-interview/issues/22)에서 관련 얘기를 했던 것이 생각나 이슈 발행합니다.

**Comment by JasonYoo1995** [comment]
- 타 회사에서 만든 주문 번호를 그대로 ID로 사용
- 자체적으로 만든 ID를 타 회사의 ID와 1:1 매핑해서 관리
- RDB의 auto increment를 사용
- DynamoDB는 쿼리 조건이 제한적 - 조합키 적극 활용
  - "Unix Epoch Time + 랜덤 UUID + User ID의 Base64인코딩 값" 등의 조합으로 **도메인 특성 상** 충돌하지 않는 ID를 생성해서 사용
  - 도메인마다 조합키 생성 방식이 다름
  - 혹시 UUID마저 충돌하면..? CS로 처리 가능한 범위
