### ISSUE TITLE
[additional] 공격적인 코드 리뷰는 나쁜 것일까?

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/Domain-Driven-Design#4]
## 연관 챕터
#1 

## 조사 내용
p.14
> 효과적으로 도메인 모델링을 수행하는 사람들도 지식을 면밀히 탐구한다. 그들은 엄청난 양의 정보 속에서 아주 미미한 관련성을 찾아낸다. 그들은 전체를 이해할 수 있는 간결한 관점을 찾아 체계적인 아이디어들을 차례로 시도해본다. 그 과정에서 수많은 모델이 시도 • **거부** • 변형된다.

위의 내용을 읽으면서, 예전에 팀에서 `공격적인` 코드 리뷰에 대해 이야기를 한 것이 떠올랐습니다.
관련하여 여러분의 생각을 들어보고 싶은데, 자세한 이야기는 스터디 시간에 공유드리도록 하겠습니다.

**Comment by JasonYoo1995** [comment]
- 좋습니다 < 좋을 것 같습니다 < 좋을 것 같긴 합니다 < 좋은 것 같긴 하지만, 다른 의견이 있다면 제시해달라
- 그렇게 생각하신 이유가 뭔가요? 의도가 뭔가요?
- 너무 조심하려다가 더 좋은 답까지 도달하지 못하는 경우
- 의견은 막힘 없이 주고 받되, 말투는 조심
- 각 사람의 성향을 사전에 파악한 상태라면, 오해가 줄어들 수 있음
- 텍스트로 소통하는 경우, 해석하는 쪽에서 실제 의도에 보다 더 부정적으로 해석하는 경우가 있음

**Comment by wooyounggggg** [comment]
https://blog.banksalad.com/tech/banksalad-code-review-culture/
