### ISSUE TITLE
[question] Specification 패턴과 검증 로직 위치의 적절성

### ISSUE THREAD

**Issue by kth990303** [caffeine-library/Domain-Driven-Design#41]
## 질문

#40 에 제가 적은 keyword issue 코멘트에서 이어지는 질문입니다.
그렇기 때문에 해당 코멘트에 언급된 책의 내용을 여기에도 첨부한 후, 제 질문을 적어보겠습니다.

> SPECIFICATION을 이용하면 규칙을 도메인 계층에 유지할 수 있다. 아울러 완전한 객체를 사용해서 규칙을 표현하므로 설계가 모델을 더욱 명확하게 반영할 수 있다. (p. 241)

> 특별한 목적을 위해 술어와 유사한 명시적인 VALUE OBJECT 를 만들어라. SPECIFICATION 은 어떤 객체가 특정 기준을 만족하는지 판단하는 술어다. (p. 240)

실제로 저는 검증 로직을 도메인 내에 메서드 분리를 통해 실시하거나, embedded된 값 객체(c.f. VO) 내에서 검증하곤 했습니다.
다만 **완전히 검증만을 위한 utils성 클래스라든지 별도의 명세 클래스를 만든 적은 없었던 것 같아요**. 241쪽에 언급된 내용처럼 규칙을 도메인 계층에 유지해야된다고 생각했기 때문에 그랬던 듯합니다. 

하지만 책에서 소개된 SPECIFICATION 패턴은 명세 검증만을 위한 별도의 utils 클래스를 만드는 것 역시 좋은 패턴이라고 소개하는 것 같이 느껴졌습니다. p.242에 `isSatisfiedBy(Invoice): Boolean` 메서드만을 가진 `Invoice Specification` 클래스가 소개돼있고, p.244에 `isSatisfiedBy(Invoice): Boolean` 메서드는 단순 검증 필터링을 목적으로 하는 (아예 static method로도 사용될 수 있어보이는) utils 클래스 느낌이라 생각했습니다. 

저는 여기서 **이러한 utils 클래스를 별도로 분리하는 것이 과연 좋을까? 라는 생각**이 들었습니다.
241쪽에 언급됐던 것처럼 규칙을 도메인에 유지해야된다고 생각하는데, utils 클래스는 도메인 계층에 위임했다기엔 좀 애매하지 않나 싶다는 생각이 들었기 때문이에요. 

요약하자면 질문은 아래와 같습니다.
1. SPECIFICATION 패턴은 VO 객체에 검증 로직 위임, utils 클래스 생성을 통한 검증 객체 생성 등을 포함한 패턴이 맞는지?
2. 맞다면 utils 클래스 생성 또는 아예 별도의 검증 객체를 생성하는 것이 과연 좋은 것일지?

## 연관 챕터

#39

**Comment by wooyounggggg** [comment]
**utils성 클래스의 의미**가 사람마다 달라서 그 의미가 모호한 것 같은데요, 저는 대략 아래와 같은 의미로 생각하고 있습니다.
> 계층(domain, infra, app, presentation 등)에 관계없이, 편의를 위해 특정 기능들을 묶음으로 제공하기 위한 범용 클래스

대표적인 utils성 클래스는 StringUtils.java가 있을 것 같습니다.

```java
public class StringUtils {
    ...

    public static boolean isEmpty(String str) {
        return str == null || str.length() == 0;
    }
...
}
```

반면 Specification은 범용적 편의성 기능을 제공하는 것보다는, 도메인 무결성을 위한 '정책'을 클래스로 개념화한 것이라고 생각합니다.(책에서 이야기하는 `암시적인 개념을 명확하게`의 일환이라고 생각됩니다.)

조금 결이 다른 이야기지만, 테스트 코드가 함수의 기능 명세 역할을 한다고도 이야기하죠. 그와 비슷하게, Specification은 비즈니스 도메인이 어떤 것을 허용하고, 어떤 것을 허용하지 않는지 즉 '정책'에 대한 명세를 파악할 수 있는 수단으로도 볼 수 있을 것 같습니다.

위의 내용을 토대로 질문해주신 내용에 답변을 해보자면,

**Q) SPECIFICATION 패턴은 VO 객체에 검증 로직 위임, utils 클래스 생성을 통한 검증 객체 생성 등을 포함한 패턴이 맞는지?**
#26 에서 VO의 개념은 `도메인 엔티티를 묘사하는 값 객체`로 정의할 수 있을 것 같은데요, Specification이 entity를 설명하고 묘사하는 기능을 하는가? 라는 부분에는 개인적으로 조금 물음표가 생기지만, 책에서는 VO로 정의하는 것 같네요.
utils 클래스와는 성격이 다르다고 생각합니다.

**Q) 맞다면 utils 클래스 생성 또는 아예 별도의 검증 객체를 생성하는 것이 과연 좋은 것일지?**
기능을 메서드로 작성하기 vs 기능을 클래스로 작성하기의 문제와 동일하다고 생각합니다.
비용에 따른 trade off를 고려해서 어디서 검증할 지 정하는 것이 좋지 않을까요?

**Comment by kth990303** [comment]
오, 저는 책에서 오히려 vo보다 사실상 함수에 가까운 utils 클래스에 가까운 예제를 소개시켜줬다 생각했었어요. 뭔가 검증만 하고 별도의 책임이 없는 느낌이었는데, **생각해보니 `명세 검증 자체가 해당 객체의 책임`이라 볼 수 있겠군요.** 책에서 VO로 얘기하고 있는거라면 의문이 조금 줄어드네요. 제시해주신 stringutils 예시 덕분에 p .244의 클래스가 VO로 볼 수 있겠단 생각이 드네요. 감사합니다.

말씀해주신 것처럼 `stringutils는 범용적 편의성 기능,  specification은 특정 객체에 대한 명세 및 정책 느낌`이라 생각들어요. 그렇기 때문에 저는 specification 관련은 함수가 아닌 메서드로 사용(vo 값 객체를 가져서 검증하거나, 도메인 검증 메서드와 같은 방법으로)하는 것이 별도 utils 클래스 검증보다 객체의 자율성, 응집성 면에서 좋다고 생각들었어요.
