### ISSUE TITLE
[discussion] dangling pointer

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/Domain-Driven-Design#45]
## 토론 주제
dangling pointer

## 토론 내용
서비스를 운영하면서, 참조될 가능성이 없는(사용되지 않는) dangling pointer를(저희는 가비지 리소스라고 부릅니다) 일괄적으로 배치를 통해 검출해내는 로직을 구현하였습니다. 기능을 구현하면서, 다른 팀에서는 서비스 내 어딘가에 존재하는 dangling pointer를 어떻게 처리하고 있는지 궁금했는데요. 혹시 다른 팀에서는 어떻게 처리하고 있는지 궁금합니다 😄

**Comment by JasonYoo1995** [comment]
- 팀 내에서 히스토리 확인 (구두, 문서, 로그 등)
- 팀 외부 유관 부서 확인
- 제거 근거 자료 문서화

**Comment by emiling** [comment]
- 이전 로그/데이터에 대한 관리
  - airflow : 특정 주기, DAG을 정의하여 프로세스 실행 
  - AWS Athena : 일정 주기 이전 데이터는 athena로 조회
- GC 튜닝에 대한 경험? 
- API fadeout을 위한 이전 데이터 조회
  - user-agent 같은 것들 같이 조회
  - API token 발급
