### ISSUE TITLE
[question] 도메인 모델의 형태

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/Domain-Driven-Design#5]
## 질문
1장을 읽으면서, 결국 책에서 하려는 이야기는 도메인 모델을 잘 정의하고 지속적인 상호작용을 통해 꾸준히 발전시켜야 한다는 것으로 이해했습니다.
반면 팀에서 업무를 하면서 느낀 것은, 팀에 명쾌하게 정의되어 있는 도메인 모델은 없고, 구성원들이 남긴 문서나 그들의 머리속 등 여러 곳에 파편화 되어있는 것 같습니다.

그렇게 된 것의 이유로는 아래와 같은 것들이 생각나는데요.
- DDD의 개념을 이해하기 전에 프로젝트가 시작됨
- 도메인의 범위가 넓고, 도메인 전문가가 굉장히 많음
    - IaaS, DBA, 서비스 운영팀, ...
- 일이 바쁨
- ...

여러분들의 팀이나 프로젝트에서는 도메인 모델을 어떻게 관리하고 계신지 궁금합니다.

## 연관 챕터
#1

**Comment by JasonYoo1995** [comment]
팀에서 진행 중인 프로젝트에서 사용하고 있는 DDD적인 요소에는 무엇이 있는지 공유해주시고
DDD적인 관점에서 바람직하지 않아 리팩토링이 필요한 지점이 있다면 함께 공유해서
개선 방향을 구상해봐도 좋을 것 같습니다.

(은총알은 없다는 말처럼 DDD가 무조건 좋은 것은 아니고
우리의 프로젝트가 DDD를 지키지 않는다고 해서 수준이 낮은 프로젝트인 것도 아닙니다.
다만, 우리의 프로젝트를 DDD적인 관점에서 해석해보는 과정 자체가
DDD의 장점과 단점을 파악하는 데에 한층 더 도움이 될 거라고 생각합니다.)

**Comment by leejaeseung** [comment]
이벤트 스토밍 내용 공유
