### ISSUE TITLE
[keyword] 11장 분석 패턴의 적용

### ISSUE THREAD

**Issue by emiling** [caffeine-library/Domain-Driven-Design#52]
## 주제

'11장 분석 패턴의 적용'을 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터

https://github.com/caffeine-library/Domain-Driven-Design/issues/51

**Comment by leejaeseung** [comment]
## 분석 패턴은 참고할 수 있는 지식이다.
> 운 좋게 적용 가능한 분석 패턴을 알고 있더라도 분석 패턴이 현재의 특정 요구사항에 딱 들어 맞는 경우는 거의 없다. 그럼에도 분석 패턴은 도메인을 파악하는 과정에서 훌륭한 길잡이 역할을 하며 깔끔하게 추상화된 어휘집을 제공한다.

**추상화된 어휘집을 제공한다.** 가 제일 와닿았던 것 같아요. 패턴 공부를 소홀히 하다 최근에 패턴 책을 읽고 있는데, 장황하게 설명될 내용이 패턴명 하나로 함축되니 코드를 짤 때 뿐만 아니라 팀원과 커뮤니케이션할 때도 큰 도움이 되겠더라구요.

그동안 패턴에 대해 대략적으로만 알고 있었고 패턴 얘기가 나오면 머릿속에 잘 그려지지 않았어서, 패턴과 그 패턴에 대한 저만의 한 줄 요약을 만들면서 공부하고 있습니다.
다른 분들은 패턴 공부를 어떻게 하시는지 궁금합니다!

**Comment by emiling** [comment]
### 분석 패턴 [Fowler 1997. p.8] 
> - 업무 모델링 과정에서 발견되는 공통적인 구조를 표현하는 개념의 집합
> - 단 하나의 도메인에서만 적절할 수도 있고 여러 도메인에 걸쳐 적용이 가능하다

정의에서도 볼 수 있듯 생판 모르는(명백하지 않은) 도메인에 대한 소프트웨어를 작성할 때 
기술적으로 보다 개념적으로 해당 도메인 파악에 도움을 주고 
이런 식으로도 모델을 작성해볼 수 있다 라는 가이드(스타터팩..?) 라는 인상을 받았습니다.

즉 전술적인 해법이라기 보다 전략적인 해법에 대한 여러 보편적 패턴을 제시하고 
이걸 잘 짜맞춰서 적용해볼 수 있고 이걸 계속 하다보면 통찰력을 기를 수 있다고 읽히네요.

> 대부분의 모델 에서 근본 아이디어는 얻을 수 있을지 몰라도 분석 패턴의 큰 가치라고 할 수 있는 **선택의 배경이 된 논리와 그에 따르는 영향력까지 제공**하는 모델의 수는 손에 꼽을 정도롤 적다
