### ISSUE TITLE
[question] Soft delete 데이터의 검색 조건 강제화

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/Domain-Driven-Design#56]
## 질문

서비스에서 Hard Delete 안하는데, 데이터를 가져오거나 검색할 때 delete_yn = 'N' 조건을 반드시 명시해야하는데
가끔 이런 조건을 누락하여 수행하는 경우가 있는데 이런 경우 누락없이 검색할 수 있는 방법?

## 연관 챕터

#{연관 issue 번호}

**Comment by emiling** [comment]
- mongo updateAt : 매번 update 할 때마다 현재 시간을 매번 업데이트하는 경우 유사한 상황
  - n억건 이상 가는 경우 primary second 사이의 데이터 누락 : **primary <-> second 바뀌는 경우 발생** (동기화 옵션)
- DSL을 생성할 때 추가하는 형식으로하면 누락을 방지할 수 있음
  - 히스토리성 데이터는 기간 정책을 두고 주기적 삭제(+ 수동삭제, 조회 기간을 제한), HDFS 등 사용
  - ES : warm data , cold data
