### ISSUE TITLE
[question] DDD의 정의, DDD의 범위

### ISSUE THREAD

**Issue by JasonYoo1995** [caffeine-library/Domain-Driven-Design#6]
## 토론 주제

DDD에서는 유비쿼터스 언어가 의사소통에서 중요하다고 합니다.
그런데 저는 아직 DDD라는 단어의 정의와 범위가 정리되지 않았습니다.
아마 스터디원들 사이에서도 DDD라는 단어에 대한 이해가 조금씩 다를 거라고 생각합니다.
서로가 생각하는 DDD의 정의와 범위를 공유해보고, 그 차이를 좁히고 의미를 통일해서
스터디에서 DDD라는 단어도 방언이 아닌 유비쿼터스 언어로 통했으면 좋겠습니다.

각자가 생각하는 DDD의 정의와 범위를 공유 부탁 드립니다.

**Comment by emiling** [comment]
최근에 https://www.youtube.com/watch?v=pMuiVlnGqjk 이 영상을 좀 보고 있는데 댓글중에 좀 와닿는 코멘트가 있어 공유합니다.

> Have in mind that DDD is a set of guiding principles that presents tools since the code level (you may have heard about value objects) up to a strategical level (when designing teams around bounded contexts) - and doing all that by focusing on the core domain and having a shared view of the problem space with the domain experts.

**Comment by JasonYoo1995** [comment]
좋은 영상과 문장 공유 감사합니다. 영상도 한 번 들어보겠습니다.

저는 DDD를 '도메인의 요구사항이 변경되면서 복잡도가 점점 늘어나도 이를 효과적으로 대처할 수 있는 소프트웨어 방법론들'이라고 정의 내려볼 수도 있을 것 같다는 생각이 드는데 그렇다면 DDD의 범주가 굉장히 넓다는 생각이 듭니다.

Aggregate, Bounded Context, Value Object 등 모델을 소프트웨어로 실체화 시킬 때 사용하는 용어들도 DDD의 범주에 들어가고

이벤트 스토밍 등 도메인을 모델화 시킬 때 도메인 전문가와 분석가, 개발자가 함께 유비쿼터스 언어로 정제하는 과정도 DDD의 범주에 들어가고

서버 내 아키텍처인 Layered Architecture, Clean Architecture, Hexagonal Architecture와, 서버 간 아키텍처인 Micro Service Architecture도 모두 도메인의 복잡성을 효과적으로 다루기 위해 사용하는 서버 아키텍처 패턴들이므로 DDD의 범주에 들어간다고 볼 수 있을 것 같습니다.

**Comment by JasonYoo1995** [comment]
저는 DDD를 '도메인의 요구사항이 변경되면서 복잡도가 점점 늘어나도 이를 효과적으로 대처할 수 있도록 도메인의 요소들을 소프트웨어 안에 녹여놓는 기법과 방법론들'이라고 정의 내려보았습니다. DDD의 범주가 굉장히 넓다고 느껴집니다.

Aggregate, Bounded Context, Value Object 등의 용어들도 DDD의 범주에 들어가고

이벤트 스토밍 등 도메인을 모델화 시킬 때 도메인 전문가와 분석가, 개발자가 함께 유비쿼터스 언어로 정제하는 과정도 DDD의 범주에 들어가고

서버 내 아키텍처인 Layered Architecture, Clean Architecture, Hexagonal Architecture와, 서버 간 아키텍처인 Micro Service Architecture도 모두 도메인의 복잡성을 효과적으로 다루기 위해 사용하는 서버 아키텍처 패턴들이므로 DDD의 범주에 들어간다고 볼 수 있을 것 같습니다.

복잡하고 방대해보이지만, 결국 DDD는 '전략적 설계와 전술적 설계에서 필요한 모든 것'이라고 단순하게 요약해볼 수도 있을 것 같네요

**Comment by leejaeseung** [comment]
"Which one is more useful?" - great question to use in an event storming session. It's conveying that modelling is about the usefulness of it for the problem being solved, not about the soundness of the model per se.

유진님이 공유해주신 영상 댓글에서 좋은 댓글을 찾았는데, 위 댓글이 DDD 를 관통하는 말이지 않나 싶네요.

DDD 란 "좋은 모델을 만드는 것이 아닌 문제 해결에 가장 유용한 모델을 찾는 것"
