### ISSUE TITLE
[keyword] 17장 전략의 종합

### ISSUE THREAD

**Issue by leejaeseung** [caffeine-library/Domain-Driven-Design#70]
## 주제

'17 - 전략의 종합'을 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터

https://github.com/caffeine-library/Domain-Driven-Design/issues/69

**Comment by emiling** [comment]
### 전략의 종합 
- 전략적 설계의 세 가지 기본원칙 (컨텍스트, 디스틸레이션, 대규모 구조)은 서로 보완하며 상호작용 한다
  - 대규모 구조와 컨텍스트 : 하나의 CONTEXT 하위의 모델 요소나 하위 시스템 인터페이스를 LAYER로 정리 가능
  - 대규모 구조와 디스틸레이션 : CORE DOMAIN 안의 각종 관계와 GENERIC SUBDOMAIN 사이의 관계를 설명하는데 도움  

### 누가 전략을 세우는가? 
- 어플리케이션 개발에서 창발하는 구조 
   - 소통 능력이 뛰어나고 자기 훈련을 행하는 팀은 중앙통제 없이 운영 되어 일련의 원칙에 도달
   - 질서가 아닌 명령에 의해서가 아닌 유기적으로 성장하게 됨
   - 실천적인 개발자에 의한 자발적 전략적 설계 리더십이 발생
- 고객(어플리케이션 개발팀) 중심의 아키텍처 팀 
  - 아키텍처가 개발의 협력자로써 개발자와 함께 패턴을 발견하고 디스틸레이션에 도달
  - 어플리케이션 개발과 동등한 위치에서 일하며 개발을 강조하는 태도를 가져야함

### 전략적 설계 결정을 위한 6가지 요소
- 의사 결정은 팀 전체로 퍼져야 한다
  - 관리조직에서 부여한 권위(상아탑 아키텍트)보다 개발자들이 전략에 대해 갖는 실제 관계에 더 관심을 귀기울여야함
- 의사결정 프로세스는 피드백을 흡수해야 한다
  - 전략적 설계 과정에서 프로젝트의 요구와 도메인 개념을 진정으로 깊게 이해하는 어플리케이션 개발팀 구성원들도 관여해야함
- 계획은 발전을 감안해야한다
  - 설계 결정을 미리 정하지 말고 개발 프로젝트 과정에서 통찰력이 깊어짐에 따라 지속적으로 변화하도록 해야함
  - 혁신은 강력한 피드백과 함께 어플리케이션 개발 과정에서 장애물을 만나거나 예상치 못한 기회를 발견할 때 나타남
- 아키텍처 팀에서 가장 뛰어나고 똑똑한 사람들을 모두 데려가선 안된다
  - 전략팀에서 훌룡한 설계를 만들어도 어플리케이션 팀에서 그것을 따를만한 설계적 정교함을 갖추지 못할 수 있음 
- **전략적 설계에는 최소주의와 겸손이 필요하다**
  - 설계의 명료함을 대폭 향상시키지 않는 것은 아무것도 포함하지 않도록 축소한 구성 원칙과 핵심 모델을 만들어내고자 노력해야함
  - 또한 나의 생각이 누군가에겐 방해요소가 될 수 있다는 사실 깨달으려면 겸손이 필요하다
- 객체는 전문가, 개발자는 다방면에 지식이 풍부한 사람
  - 객체에게는 분명하고 한정된 책임을 부여하고 상호 의존성을 최대한 줄이되
  - 개발자는 다방면에 지식이 풍부한 사람이 되게 하라 (개발자 : 프레임워크 / 아키텍트 : 어플리케이션 코드 )
    - 좋은 프로젝트에서는 많은 사람들이 다른 사람 업무에 관여한다  

### 기술 프레임워크 설계
- 인프라스트럭처 계층을 제공하여 기본적인 서비스 구현에서 벗어나게 해주고 도메인 관심사를 격리
- 그러나 도메인 모델에 대한 표현력 있는 구현과 손쉬운 변경을 방해할 수 있음
- 실제 사용할 사람이 필요한, 기대하는 바가 충족된 프레임워크를 만들어야함

### 종합계획을 조심하라
- 전체적인 질서를 만들어 경직되고 변경이 어려운 형태의 종합 계획이 아니라
- **점진적으로 성장**하면서 적용될 수 있는 일련의 원칙을 제시하라
