### ISSUE TITLE
[keyword] 2장 - 의사 소통과 언어 사용

### ISSUE THREAD

**Issue by emiling** [caffeine-library/Domain-Driven-Design#9]
## 주제

'2장. 의사 소통과 언어 사용'을 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터

#8

**Comment by wooyounggggg** [comment]
## p.26
> Ubiquitous Language를 지속적으로 사용하다 보면 모델의 취약점이 드러날 것이다. 팀은 실험을 토대로 부자연스러운 용어나 결합의 대안을 찾아낼 것이다. 언어에 공백이 발견되면 토론하는 가운데 새로운 단어가 나타날 것이다. 이러안 **언어의 변화는 도메인 모델의 변화로 인식**될 것이며, 용어의 의미가 바뀌면 팀에서는 클래스 다이어그램을 수정하고 코드상의 클래스와 메서드의 이름을 변경하며, 심지어 동작 방식도 바꿀 것이다.

Ubiquitous Language를 지속적으로 사용하는 과정에서, Ubiquitous Language -> 도메인 모델에 피드백이 될 수 있음.
Ubiquitous Language는 그저 용어 사전이 아닌, 도메인 모델과 결합되어 도메인 모델을 진화시키는 요소임을 인식하고 있어야 함

**Comment by leejaeseung** [comment]
## p.36, p.37
> **설계의 생생한 세부사항은 코드에 담긴다.**
> **모델은 다이어그램이 아니라는 점을 항상 명심해야 한다.** 다이어그램의 목적은 모델을 전달하고 설명하는 데 있다. 코드는 설계의 세부사항에 대한 저장소 역할을 할 수 있다.

모델에 대한 너무 자세한 설계는 오히려 독이 될 수 있다.
모델에 세부사항을 모두 집어넣는 건 설계 단계에서 코드를 짜는 것과 같은데, 실제로 코드를 짤 때 이러한 내용들은 쉽게 바뀌기 
마련이다. 모델의 세부사항과 코드 간의 불일치가 생길 여지가 크다.

모델은 쉽게 바뀔 수 있어야 하고, 실제로 설계 단계에서 매우 많이 변경된다. 세부사항까지 세세하게 정의된 모델은 잦은 변경에 대응하기 힘들고, 심하면 세부사항때문에 좋지 않은 설계를 할 가능성도 있을 듯 하다.
(미리 작성된 세부사항을 만족시키려 불필요한 설계를 할 수도 있겠죠)

**Comment by emiling** [comment]
> 모델의 개념을 혼란스럽게 만드는 번역은 해로운 코드 리팩터링으로 이어진다. 의사소통이 직접적으로 일어나지 않아 개념이 분열돼도 이 같은 상태가 겉으로 드러나지 않는다. 즉, 팀원들이 용어를 다르게 써도 그것을 알아차리지 못한다. 결과적으로 **조화가 깨진, 신뢰할 수 없는 소프트웨어가 만들어진다.** (p.25)

팀원(개발자, 도메인 전문가 모두)간의 모델에 대한 합의가 제대로 이루어지지 않으면 같은 의도로 말을 해도 다른 언어를 사용하기 때문에
그 의미가 제대로 전달되지 않을 수 있고, 그 언어의 간극을 다시 번역하여 이해하는데 더 많은 비용이 발생함.
그리고 반복된 간극으로부터 발생한 오해는 결국 신뢰할 수 없는 모델을 만들고 소프트웨어의 일관성을 해친다.

> 언어의 변화는 곧 도메인 모델의 변화로 인식된다 (p.26)

#### 모델 구성의 시작점?
- 책을 읽으면서 들었던 의문점 중 하나였는데요 🤔
- "팀 내에서 모델을 구성하고자 할 때 그럼 뭐부터 시작해야할까?"  에 대한 대답이 어렴풋이 제시된 것 같습니다.

> 개발자와 도메인 전문가는 **시나리오**를 토대로 모델 객체를 단계적으로 사용해보면서 비공식적으로 모델을 시험해볼 수 있다. (p.33)

여기서 **시나리오**라는 단어가 좀 와닿았는데요. 
결국 우리가 어떤 문제를 풀고자 하고 해당 문제에 대한 구체적인 상황부터 정리해보는 것부터 시작하는 것을 제안하고 있습니다.

> We need some scenarios some specific stories about the business that tell us we’re going to use this thing for

> This model would be helpful for what for a specific use and kind of problem

아래 ([예시](https://learn.microsoft.com/en-us/azure/architecture/microservices/model/tactical-ddd))는 DDD를 활용하는 구체적인 예시가 있어 같이 첨부합니다. 
시나리오를 우선 정리한 뒤에 위 시나리오로부터 나온 **엔티티**와 **값 객체**를 식별합니다.

<img width="898" alt="스크린샷 2023-01-15 오후 5 43 32" src="https://user-images.githubusercontent.com/30731518/212531426-92e42332-b3aa-43f7-92a7-1df61cf5acca.png">

**Comment by JasonYoo1995** [comment]
<img src=https://user-images.githubusercontent.com/66045861/212533257-3fba0d69-2c37-4f61-986b-e26d62ad3a08.png>

**모델의 정제 과정**
1. 도메인 전문가 : 자신이 속한 '전문 분야'의 '전문 용어'를 기반으로 모델 구성 및 설계
2. 개발자 : '구현'의 맥락에서 모순을 없애는 방향으로 모델 개선
3. 도메인 전문가 : 도메인을 이해하는 데 부자연스럽고 부정확한 용어에 대해 반대 의사 표현
4. 개발자 : '설계'를 어렵게 만드는 모호함과 불일치에 대한 의사 표현

**UL과 모델의 관계**
- 유비쿼터스 언어에서의 단어와 구절의 의미 = 모델을 구성하는 요소의 의미
- 유비쿼터스 언어의 변화 = 모델의 변화

**2가지 대화**
- 정제된 모델과 UL 없이 대화 : 대화가 장황해지고 전달력이 모호해진다
- 정제된 모델과 UL을 활용한 대화 : 대화가 간결하고 전달이 정확해진다

**모델의 정제 방법**
- 다이어그램이나 문서로 표현했을 때 자연스러운가?
- 구두로 말했을 때 자연스러운가?

**Comment by JasonYoo1995** [comment]
<img src=https://user-images.githubusercontent.com/66045861/212533747-388885d3-ac70-40f2-9b33-5d00f13ff132.png>

- p.32에서 `모델의 요소와 상호작용`이라는 표현
  - **요소** = 명사 = 도메인 객체에 대응되는 대상
  - **상호작용** = 동사 = 도메인 객체들 간의 행위
- 저희 팀은 **상호작용** 측면에서 UL을 적극적으로 사용하고 있으며
  이를 통해 의사소통에서 높은 효율이 생김을 느끼고 있습니다.
- QA와 협업할 때도 UL의 유무는 효율에 큰 영향을 끼치는 것 같습니다.

**Comment by JasonYoo1995** [comment]
**화물 운송 관련 용어 정리**
- 통관 : 세관을 통과하는 것 (경유지)
- Leg : 구간
- 하역 : load와 unload의 개념을 둘 다 포관
  - 이 책에서는 하역이라는 단어가 unload만을 위해 쓰이는 경우도 섞여 있다
